### ISSUE TITLE
代理节点问题

### ISSUE THREAD

**Issue by xiaopihaiK** [tongcheng-security-team/NextScan#1]
根据步骤安装完代理节点，不能在管理端找到代理的地址，下拉框中没有部署的代理IP

**Comment by wukongdef** [comment]
外网环境一直不可选

**Comment by faf-xff** [comment]
> 根据步骤安装完代理节点，不能在管理端找到代理的地址，下拉框中没有部署的代理IP

没有代理IP，一般是代理节点和管理平台、etcd服务网络不通导致。

**Comment by faf-xff** [comment]
> 外网环境一直不可选

外网环境不可选，是因为部署时的配置环境为内网，如果为docker，你可以重新删除镜像下载就可以是外网。或者直接根据文档改成外网即可。https://next-scan.ly.com/install/docker/#docker-composeyaml

**Comment by ANQUSEC** [comment]
管理地址： http://127.0.0.1:80
内外网： intranet
{"level":"warn","ts":"2023-05-13T13:27:12.169+0300","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000428e00/ns-etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup ns-etcd on 127.0.0.53:53: server misbehaving\""}
2023/05/13 13:27:12 etcd start error:context deadline exceeded
