### ISSUE TITLE
服务逻辑错误: 内网没有可用的扫描节点

### ISSUE THREAD

**Issue by benniedaniel** [tongcheng-security-team/NextScan#11]
![image](https://user-images.githubusercontent.com/76260353/234490866-f6b5db8f-03cd-4e76-b9c2-856d84cc207e.png)
![image](https://user-images.githubusercontent.com/76260353/234491019-55269217-fb3d-404c-b919-e1cca3d79b40.png)

**Comment by 1uanWu** [comment]
FAQ已更新该问题解决方案
