### ISSUE TITLE
【建议】希望可以在筛选插件那里增加类似于正则表达式的搜索功能（或者是多个关键词匹配）

### ISSUE THREAD

**Issue by W01fh4cker** [tongcheng-security-team/NextScan#13]
作者的工具写的非常好！作者的想法和我前段时间想的很像，但是当时不太会写前段的界面，因此没有落地执行；  
希望可以在筛选插件那里增加类似于正则表达式的搜索功能（或者是多个关键词匹配），不然nuclei插件太多，挨个筛选要很长时间。  
作者团队辛苦啦！

**Comment by 1uanWu** [comment]
感谢提醒，后续会考虑添加
