### ISSUE TITLE
数据库错误: agent 数量不够问题

### ISSUE THREAD

**Issue by 2925298496** [tongcheng-security-team/NextScan#14]
插件管理-新增-插件测试，点击测试，提示”数据库错误: agent 数量不够“，请问是什么问题呢？后台没有打印相关的日志

**Comment by 1uanWu** [comment]
确认下env环境是否选择正确，对应env环境下agent是否存在

**Comment by 2925298496** [comment]
我是使用docker安装的

**Comment by manchesxia** [comment]
![image](https://github.com/tongcheng-security-team/NextScan/assets/17880581/5735c130-3d98-4788-9bac-7a062eded1f3)
你扫公网的话这里选2，   默认1的话会是你这个报错
