### ISSUE TITLE
docker版本启动报错，web无法启动，显示mongodb连接失败

### ISSUE THREAD

**Issue by thinkl3** [tongcheng-security-team/NextScan#20]
$ docker logs ns-admin
mgo connect occur error:[server returned error on SASL authentication step: Authentication failed.],url:[mongodb://NextScan:56074e26d5a39aad@ns-mongo:27017/NextScan]%

**Comment by 1uanWu** [comment]
faq已更新

**Comment by dead5nd** [comment]
没进行过任何修改，还是报错呀
