### ISSUE TITLE
扫描的时候卡住了，显示所有插件等待中

### ISSUE THREAD

**Issue by purple-WL** [tongcheng-security-team/NextScan#26]
<img width="609" alt="image" src="https://github.com/tongcheng-security-team/NextScan/assets/63894044/b79b057a-6cd6-4bf9-81cd-3d9df06c0f89">
去系统查看日志显示这样：
<img width="992" alt="image" src="https://github.com/tongcheng-security-team/NextScan/assets/63894044/a03ea803-ad80-4cd3-ab81-a2b68b2ef55a">
error 00:00 - complete task error:BSON field 'update.updates.u' is the wrong type 'array', 
expected type 'object'

**Comment by 1uanWu** [comment]
新版本以更新

**Comment by faf-xff** [comment]
确定你的mongo版本为4.2.x。
