### ISSUE TITLE
错误信息: 外网没有可以用的爬虫节点

### ISSUE THREAD

**Issue by Ggasdfg321** [tongcheng-security-team/NextScan#27]
<img width="1594" alt="image" src="https://github.com/tongcheng-security-team/NextScan/assets/65237278/88109aac-7547-4de2-974b-ce422c7a95f8">
目标地址我填写http://www.xxx.com，然后只开启了爬虫，没有开启扫描，就显示这个报错

**Comment by manchesxia** [comment]
看部署文档，把 爬虫服务对应配置 那段 配置到yaml里
