### ISSUE TITLE
接入AWVS Xray等扫描方式

### ISSUE THREAD

**Issue by eggdkk** [tongcheng-security-team/NextScan#33]
RT，AWVS和Xray的被动扫描是比较优秀的扫描方式，是否有排期接入嘞~

**Comment by dean2021** [comment]
> RT，AWVS和Xray的被动扫描是比较优秀的扫描方式，是否有排期接入嘞~

nextscan是支持被动扫描的，详情文档：https://next-scan.ly.com/user-guide/project/#http

ps：nextscan设计之初参考了AWVS、Xray、Nessus 三款扫描器，齐聚了这三款扫描器的特色，具体可以详情文档
