### ISSUE TITLE
扫描任务卡住

### ISSUE THREAD

**Issue by FuckAllWorld** [tongcheng-security-team/NextScan#5]
插件数量：20+
URL数量：40+

配置使用"扫描模版",运行50分钟任务都没有结束

<img width="307" alt="截屏2023-04-25 12 12 34" src="https://user-images.githubusercontent.com/42711299/234172772-701a7231-a8d9-46a2-b8c1-2f8abfee896e.png">

**Comment by faf-xff** [comment]
这个目前看已经运行异常了，可以看下详情的错误日志
