### ISSUE TITLE
扫描&爬虫节点部署问题

### ISSUE THREAD

**Issue by ahmatjan** [tongcheng-security-team/NextScan#8]
参考部署文档 https://next-scan.ly.com/install/binary/#2

1、https证书错误问题（自签名），加个启动参数由用户控制是否进行证书校验吧
![image](https://user-images.githubusercontent.com/10572348/234319277-e270a5fb-c9ad-4459-8acb-6407e24f1111.png)

2、建议针对agent上线加一个类似邀请码or临时token。
<img width="539" alt="1682434792069" src="https://user-images.githubusercontent.com/10572348/234318555-6ee61339-e1a7-4fa0-8659-edda08f5f95c.png">

**Comment by faf-xff** [comment]
好的，下次升级我们会修复
