### ISSUE TITLE
ns-admin存在bug问题

### ISSUE THREAD

**Issue by ahmatjan** [tongcheng-security-team/NextScan#9]
1、后台针对节点的管理，IP重复直接合并了，建议换个维度管理，比如uuid打agent标签
![image](https://user-images.githubusercontent.com/10572348/234322262-eea225de-41eb-410b-bc03-d35166b1c425.png)

2、minio在实际使用时，节点需要能联通，文档没写，改个文档？
![image](https://user-images.githubusercontent.com/10572348/234322705-9259b11a-e036-466b-952b-5850babcf982.png)

**Comment by faf-xff** [comment]
好的，这个IP是个问题，我们下次升级会调整。文档也会做相应更改
